### ISSUE TITLE
Sonos iOS app is broken

### ISSUE THREAD

**Issue by Bubu92** [BlackJack8/iOSAdblockList#15]
Hi. 

I am missing now all songs cover photos. 

Also, the connection to music services is impossible. 

Thanks.

**Comment by BlackJack8** [comment]
Hey there! Since i don‘t have a Sonos speaker, i need your help.
May you send me a screenshot of the whole dns proxy list after the Sonos app gets broken? 
But remember to clear the list before that.

Is that all happening in the Sonos app or somewhere else too?

**Comment by Bubu92** [comment]
Thanks for your response. 

In fact, I spent hours to figure out what was wrong. 
I used your file in Adblock and it is where I was facing some issues with Sonos. 
However, I tried the same configuration with DNScloak and it is working fine. 

Also, I am sorry if I incrimated too quickly  your file which in fact seems fine. This issue is coming from Adblock. Unfortunately I could not find the solution yet and I am still waiting for Adblock support feedback. 

Thanks again. 

Sent from my iPhone

On 14 Apr 2019, at 19:50, BlackJack8 <notifications@github.com> wrote:

Hey there! Since i don‘t have a Sonos speaker, i need your help.
May you send me a screenshot of the whole dns proxy list after the Sonos app gets broken?
But remember to clear the list before that.

Is that all happening in the Sonos app or somewhere else too?

**Comment by BlackJack8** [comment]
No problem!
My list already has the important domains from the pre-installed groups integrated. That means you can delete all of them and just use my list.

**Comment by Bubu92** [comment]
Thanks for your answer.

However I am not sure we are talking about the same application because there is n o pre-installed groups integrated. 
In fact I am referring to this application that comes empty with no Hosts file uploaded.

https://www.adblockios.com <https://www.adblockios.com/>

**Comment by BlackJack8** [comment]
Yes, i‘m talking about Adblock by futuremind. It normally comes with preinstalled groups like Global, Chinese Adservers etc.

**Comment by BlackJack8** [comment]
There is a different method, but only using a Computer. Do you want me to tell how to do it?

**Comment by Quorum75** [comment]
A computer for the iPhone? I am listening :)

**Comment by Quorum75** [comment]
By the way what your opinion on this HUGE :)) Host file `https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist`

**Comment by BlackJack8** [comment]
This one is not iOS based.

**Comment by Quorum75** [comment]
OK. 

So what is your alternative method you are talking about?

Sent from my iPad Pro

On 18 Apr 2019, at 00:00, BlackJack8 <notifications@github.com> wrote:

This one is not iOS based.

**Comment by BlackJack8** [comment]
A method to track network usage from the phone by a computer. Charlesproxy is a good program for that.
I meant the Blocklist, because it is only Windows and Linux based.

**Comment by Quorum75** [comment]
I checked their page but honestly I have no use of such tool because I am looking for an iOS app which will create a local proxy, like Adblock, on my iPhone. 

On my Mac everything is under control from a DNS - Host - IP security and privacy point of view.
The only thing that will help me is to get a Host file manager application to merge Host files and remove duplicates. Unfortunately there is no such tool on OSX platform that does that.

On the iPhone, at the present time I am using DNSCloak which let me choose a DNS (personally I am using Adguard Family DoH) and let me upload my Host file (yours merged with StevenBlack one).
However this configuration, as mentioned previously, in not 100% suitable because the DNS traffic does not go through the VPN tunnel.

That is why Adblock, with their local proxy was a good solution because it does interfere with the VPN DNS.
BTW I had few back and forth discussions with Adblock developers but they don’t understand anything regarding my issue with Sonos and never answer to the question. It is very annoying. Unfortunately I do not speak polish :(

**Comment by BlackJack8** [comment]
Ok. But iOS is pretty limited with this sadly. So you are using StevenBlacks list with your iPhone? Just to let you know, this list is not based on iOS or iOS games either. I don't use DNSCloak, but this huge list might slow your device down.

The support of Adblock is trash, i know :/ i can speak polish but even then they won't fix anything.

**Comment by Quorum75** [comment]
I guess I did not connect the dots. I don’t understand the tracking thing with the computer and the iPhone Do you mind to explain?

I use StevenBlack lists in order to block porn, social, gambling…. websites. I have an iPhone XS Max and with the Host active or not I do not see any difference. I have about 54K domains blocked at the present time. 

You should check DNSCloak, it is free, if you do not use a VPN. They provide dozen of DNS servers.

Anyway what app do you use on you iPhone to import your Host file?

**Comment by BlackJack8** [comment]
You connect your iPhone to a Proxy which is directed through Charlesproxy. Then it can track your network.
I have DNS Cloak but i don't use it.
For importing i use Adblock's native importing feature. I can't think of anything similar :/

**Comment by Quorum75** [comment]
Got it but it means you must leave your computer always on, correct? If so, it is something I cannot do. 

Regarding DNSCloack I found it far more better to import a Host file. It is instantly. 
With Adblock it took me 48H! 👎🏻

Also, I fou ND that Adguard was the only one to block ads within iOS app. The team seems to be pretty good. 
They realized a "Home" application version but here again you need a computer always on. So. Not good for my own configuration. 

It is really a.pain we can't access to iOS Host. 

Sent from my iPhone

On 18 Apr 2019, at 22:56, BlackJack8 <notifications@github.com> wrote:

You connect your iPhone to a Proxy which is directed through Charlesproxy. Then it can track your network.
I have DNS Cloak but i don't use it.
For importing i use Adblock's native importing feature. I can't think of anything similar :/
