### ISSUE TITLE
Correct URL to block list for iOS Adblock 

### ISSUE THREAD

**Issue by 0000011110110111** [BlackJack8/iOSAdblockList#26]
I can’t seem to get the right url to the list for iOS Adblock. I keep getting an error message that the list has to be Easylist format. Please help.

**Comment by BlackJack8** [comment]
Which Adblocker are you using?

The Easylist format is different from others, that's why.

**Comment by 0000011110110111** [comment]
I’m using AdBlock: https://apps.apple.com/fr/app/adblock/id691121579?l=en

Sorry I couldn’t back to you earlier.

**Comment by BlackJack8** [comment]
Oh i know what the issue is.
You wanted to import the domains to the Safari Content Blocker; You actually need to click on "Import DNS rules" it in the settings.
But first, create a separate group under: Manage DNS Rules -> (Click on the active tab) -> Scroll down and click on "Add Group".
Then go back to the settings and click on "Import DNS rules". Select the group you've created.
Done!
Make sure you use this domain for importing:
https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt

**Comment by 0000011110110111** [comment]
Thanks very much. 👍. That worked.
