### ISSUE TITLE
Blocked domain breaks Google's MAP traffic details and commute.

### ISSUE THREAD

**Issue by asaddon** [BlackJack8/iOSAdblockList#8]
**clients.l.google.com** domain in the list breaks Google Maps traffic information and commute.

Also as I said in my last issue [report](https://github.com/BlackJack8/iOSAdblockList/issues/7#issue-401859626) **s3.amazonaws.com** is blocked and IMO it shouldn't since it breaks many websites.

**s3.amazonaws.com** is an endpoint for a [cloud file storage product](https://aws.amazon.com/s3/) offered by Amazon Web Services (AWS) and is used by many websites and apps (albeit usually behind the scenes, but you can serve files from it directly too).

**Comment by BlackJack8** [comment]
Wow didnt know clients.l.google.com was in the list. I know that it can break stuff, but as i don‘t use Google Maps i didnt notice it.
And yeah... s3 also serves ads. I didnt find any website being bricked by blocking this domain, and since it‘s for ad serving i added it.
The problem with the host format is that you can only block a general domain and not specific dns requests etc. 
And amazons s3 service is a good example for that.
Removed both domains now
