### ISSUE TITLE
Suggestion: Lite version of Host-List

### ISSUE THREAD

**Issue by ta6vie** [BlackJack8/iOSAdblockList#83]
I remember the host list was in the range of 4k entries. Now it reaches to 14k plus. Since updating to IOS 14 I have noticed some slow down with wait time before the links are opened. I'm not sure if this is from iOS itself or Adblock by Futuremind or the size of host-list. But the slow down is certainly noticeable compared to IOS 13. This is why I'm suggesting if possible make another lite version of host list.

**Comment by BlackJack8** [comment]
Thank you for the suggestion. Starting off, this would require a lot of time, not just because of sorting the majority of domains out, but also of maintaining two lists at the same time. If i were to add all new domains to the Lite list, it would eventually grow up to the same size.

Secondly, I've spoken with the Devs of Adblock by Futuremind regarding app optimization and speed; Just a few months ago, the app was actually pretty sluggish, but that has improved a lot with recent updates. Although they've optimized their app, the size of some lists still cause slowdowns.
I am currently using Adguard Pro and do not experience any performance impact from my list. 

I really recommend Adguard Pro, since it has a subscription feature where updates from Github are automated, and also the aforementioned performance advantage.

If that doesn't help, i'd be willing to create a Lite version of my list, which unfortunately, i will not be able to maintain.

Please let me know if you have any questions.

**Comment by ta6vie** [comment]
Thanks for the feedback. I might consider switching to Adguard Pro as I had purchased both apps. The reason I'm sticking with Adblock by Futuremind is because I bought it first then got used to it. I believe also it is much easier than Adgurad which has a lot of options. I hope that Adblock by Futuremind will be optimized to deal with large host-list.

However the request for lite option is still valid for the people who still use it. As for updating it, how long you could do it, if it is quarterly I think it is enough. At least having something better than nothing which is appreciated.

**Comment by michaelb-ae** [comment]
@ta6vie Warning if you use adguard pro, the DNS filtering is sometime very energy-hungry (since every dns request wake up the application) in my case on my Xs max, i pass from 3 day to 2 day of battery life with dns filtering.
In my case i have preferred to use a raspberry pi with adguard home and only the ads list (even if i have the pro subscription).

**Comment by BlackJack8** [comment]
I'm actually using Adguard Pro too, but mainly for management reasons. I haven't particularly noticed any excessive battery drain, but i'll test that now.

I'm also running Pihole on a Synology so i should be fine.

**Comment by michaelb-ae** [comment]
i was using pihole too befuse, but they droped the support of adguarded syntax, and if we check oisd (one of the list i used before), abp syntax are (if well done) more strict (since they incluse subdomain), and you can create list who apply for client (for instance i have some whitelist rule who allow domain on my iphone and the very same domain is locked on my laptop (@@|smp-device-content.apple.com^$client=Iphone), it the function who have pushed me to switch on adguard home (who don't requier license to work)

**Comment by ta6vie** [comment]
> @ta6vie Warning if you use adguard pro, the DNS filtering is sometime very energy-hungry (since every dns request wake up the application) in my case on my Xs max, i pass from 3 day to 2 day of battery life with dns filtering.
> In my case i have preferred to use a raspberry pi with adguard home and only the ads list for safari (even if i have the pro subscription).

Since the recommendation by @BlackJack8 I have switched to Adguard Pro with DNS filtering. I would say the battery life is the same with Adblock by Futuremind. I can't compare it with stock as haven't been without adblock app. Because simply I can't stand ads.
